In [23]:
import pandas as pd
import numpy as np

In [24]:
dados = 'CARAMELO2.csv'
df = pd.read_csv(dados, sep=';')

In [25]:
df.head()

,ID Venda,Loja,ID Loja,Estado Loja,Cidade Loja,Nome Cliente,ID Cliente,Sexo,Idade,Estado Cliente,Cidade Cliente,ID Produto,Categoria Produto,Marca,Data da Compra,Data da Entrega,Metodo de Pagamento,Produto,Valor de Venda
0,1,Melo,49,BA,Salvador,Lucas Silveira,35727,Masculino,24,BA,Vitória da Conquista,946,Eletrônicos,Lenovo,2024-12-20,2024-12-30,Pix,Drone,"4489,78"
1,10,Mendonça Machado Ltda.,7,SP,Sorocaba,Isabella Campos,2188,Feminino,41,MG,Uberlândia,112,Eletrônicos,Apple,2023-11-22,2023-11-28,Dinheiro,Celular,"11882,39"
2,1000,Cunha Mendes S.A.,97,BA,Camaçari,Marcela Barbosa,2293,Feminino,47,SP,Sorocaba,283,Alimentos,Del Valle,2023-08-25,2023-08-27,Dinheiro,Suco,"37,08"
3,100001,Nunes,77,MG,Contagem,Ravy Cunha,38559,Feminino,59,RJ,Petrópolis,805,Eletrônicos,Dell,2024-08-03,2024-08-04,Dinheiro,Notebook,"6727,57"
4,100007,Cunha Mendes S.A.,97,BA,Camaçari,Sra. Ana Cecília Pinto,19274,Masculino,27,SP,São Paulo,362,Alimentos,Coca-Cola,2023-02-28,2023-03-08,Pix,Refrigerante,"17,33"

In [26]:
df['Valor de Venda'] = df['Valor de Venda'].str.replace(',', '.').astype(float)
df.head()

,ID Venda,Loja,ID Loja,Estado Loja,Cidade Loja,Nome Cliente,ID Cliente,Sexo,Idade,Estado Cliente,Cidade Cliente,ID Produto,Categoria Produto,Marca,Data da Compra,Data da Entrega,Metodo de Pagamento,Produto,Valor de Venda
0,1,Melo,49,BA,Salvador,Lucas Silveira,35727,Masculino,24,BA,Vitória da Conquista,946,Eletrônicos,Lenovo,2024-12-20,2024-12-30,Pix,Drone,4489.78
1,10,Mendonça Machado Ltda.,7,SP,Sorocaba,Isabella Campos,2188,Feminino,41,MG,Uberlândia,112,Eletrônicos,Apple,2023-11-22,2023-11-28,Dinheiro,Celular,11882.39
2,1000,Cunha Mendes S.A.,97,BA,Camaçari,Marcela Barbosa,2293,Feminino,47,SP,Sorocaba,283,Alimentos,Del Valle,2023-08-25,2023-08-27,Dinheiro,Suco,37.08
3,100001,Nunes,77,MG,Contagem,Ravy Cunha,38559,Feminino,59,RJ,Petrópolis,805,Eletrônicos,Dell,2024-08-03,2024-08-04,Dinheiro,Notebook,6727.57
4,100007,Cunha Mendes S.A.,97,BA,Camaçari,Sra. Ana Cecília Pinto,19274,Masculino,27,SP,São Paulo,362,Alimentos,Coca-Cola,2023-02-28,2023-03-08,Pix,Refrigerante,17.33

In [27]:
df_venda_loja = df.groupby('Loja')['Valor de Venda'].sum().reset_index().sort_values(by='Valor de Venda', ascending=False)
df_venda_loja

                               Loja  Valor de Venda
10           Mendonça Machado Ltda.     11148353.64
11                          Moreira     10298861.57
17                            Sousa     10185505.18
15              Sampaio Viana Ltda.     10064612.43
19                           Vargas      9996259.63
7                             Gomes      9958761.17
0                           Andrade      9658689.03
6                         Fernandes      9515450.64
1   Aparecida da Conceição e Filhos      9494003.35
3                             Cunha      9394960.89
12                       Moura - ME      9237011.00
5                 Cunha Mendes S.A.      8959348.58
18                         Teixeira      8957194.94
13                            Nunes      8846347.32
2                           Barbosa      8840415.89
8                           Machado      8814422.95
16                           Santos      8704263.74
4                  Cunha Gomes - EI      8588818.50
14            Ribeiro Sampaio Ltda.      8533272.70
9                              Melo      8312314.05

In [28]:
array_venda_loja = np.array(df_venda_loja['Valor de Venda'])
q1_venda_loja = np.percentile(array_venda_loja, 25)
q2_venda_loja = np.percentile(array_venda_loja, 50)
q3_venda_loja = np.percentile(array_venda_loja, 75)
media_venda_loja = np.mean(array_venda_loja)
distancia_venda_loja = (media_venda_loja - q2_venda_loja) / q2_venda_loja
iqr_venda_loja = q3_venda_loja - q1_venda_loja
lim_sup_venda_loja = q3_venda_loja + (1.5 * iqr_venda_loja)
lim_inf_venda_loja = q1_venda_loja - (1.5 * iqr_venda_loja)

print(f'Q1: {q1_venda_loja}')
print(f'Q2: {q2_venda_loja}')
print(f'Q3: {q3_venda_loja}')
print(f'Média: {media_venda_loja}')
print(f'Mediana: {q2_venda_loja}')
print(f'Distância: {distancia_venda_loja}')
print(f'IQR: {iqr_venda_loja}')
print(f'Limite Superior: {lim_sup_venda_loja}')
print(f'Limite Inferior: {lim_inf_venda_loja}')

Q1: 8833917.655000001
Q2: 9315985.945
Q3: 9968135.785
Média: 9375443.360000001
Mediana: 9315985.945
Distância: 0.0063822997749274695
IQR: 1134218.129999999
Limite Superior: 11669462.979999999
Limite Inferior: 7132590.460000003

In [29]:
outliers_venda_loja = df_venda_loja.loc[(df_venda_loja['Valor de Venda'] > lim_sup_venda_loja) | (df_venda_loja['Valor de Venda'] < lim_inf_venda_loja)]
outliers_venda_loja

Empty DataFrame
Columns: [Loja, Valor de Venda]
Index: []