In [172]:
import pandas as pd
import numpy as np

In [173]:
dados = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(dados, sep= ';', encoding='latin1')

In [174]:
df['regiao'] = df['regiao'].replace({'Grande NiterÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚Â³i': 'Grande Niterói'})

In [175]:
# Exibe as primeiras linhas do dataframe (número de linhas definido entre os parênteses)
df.head()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [176]:
# Exibe as últimas linhas do dataframe (número de linhas definido entre os parênteses)
df.tail()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
37309,159,1,2026,2026m01,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,2.0,0.0,37,1,0,0,0,0,157,2
37310,165,1,2026,2026m01,33,5,Mangaratiba,3302601,Interior,0,...,3.0,0.0,32,0,0,0,0,0,234,2
37311,166,1,2026,2026m01,33,5,Angra dos Reis,3300100,Interior,2,...,10.0,0.0,98,9,1,0,0,0,713,2
37312,167,1,2026,2026m01,43,5,Paraty,3303807,Interior,1,...,3.0,0.0,25,2,0,0,0,0,258,2
37313,168,1,2026,2026m01,28,5,Rio Claro,3304409,Interior,1,...,0.0,0.0,3,0,0,0,0,0,57,2

In [177]:
#  df.groupby(variáveis qualitativas)[variáveis quantitativas].método de agrupamento quantitativo(sum()...).reset_index()
df_furto_celular_cisp = df.groupby('cisp')['furto_celular'].sum().reset_index()
df_furto_celular_cisp

     cisp  furto_celular
0       1          15487
1       4          13700
2       5          23969
3       6           6410
4       7           1485
..    ...            ...
133   159            455
134   165           1233
135   166           2580
136   167            497
137   168            121

[138 rows x 2 columns]

In [178]:
# Exibe informações gerais do dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37314 entries, 0 to 37313
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        37314 non-null  int64
 1   mes                         37314 non-null  int64
 2   ano                         37314 non-null  int64
 3   mes_ano                     37314 non-null  str
 4   aisp                        37314 non-null  int64
 5   risp                        37314 non-null  int64
 6   munic                       37314 non-null  str
 7   mcirc                       37314 non-null  int64
 8   regiao                      37314 non-null  str
 9   hom_doloso                  37314 non-null  int64
 10  lesao_corp_morte            37314 non-null  int64
 11  latrocinio                  37314 non-null  int64
 12  cvli                        37314 non-null  int64
 13  hom_por_interv_policial     37314 non-null  int64
 14  feminicidio                 2192 non-null   float64
 15  letalidade_violenta         37314 non-null  int64
 16  tentat_hom                  37314 non-null  int64
 17  tentativa_feminicidio       2192 non-null   float64
 18  lesao_corp_dolosa           37314 non-null  int64
 19  estupro                     37314 non-null  int64
 20  hom_culposo                 37314 non-null  int64
 21  lesao_corp_culposa          37314 non-null  int64
 22  roubo_transeunte            37314 non-null  int64
 23  roubo_celular               37314 non-null  int64
 24  roubo_em_coletivo           37314 non-null  int64
 25  roubo_rua                   37314 non-null  int64
 26  roubo_veiculo               37314 non-null  int64
 27  roubo_carga                 37314 non-null  int64
 28  roubo_comercio              37314 non-null  int64
 29  roubo_residencia            37314 non-null  int64
 30  roubo_banco                 37314 non-null  int64
 31  roubo_cx_eletronico         37295 non-null  float64
 32  roubo_conducao_saque        37314 non-null  int64
 33  roubo_apos_saque            37314 non-null  int64
 34  roubo_bicicleta             19925 non-null  float64
 35  outros_roubos               37314 non-null  int64
 36  total_roubos                37314 non-null  int64
 37  furto_veiculos              37314 non-null  int64
 38  furto_transeunte            37314 non-null  int64
 39  furto_coletivo              37314 non-null  int64
 40  furto_celular               37314 non-null  int64
 41  furto_bicicleta             19925 non-null  float64
 42  outros_furtos               37314 non-null  int64
 43  total_furtos                37314 non-null  int64
 44  sequestro                   37314 non-null  int64
 45  extorsao                    37314 non-null  int64
 46  sequestro_relampago         37314 non-null  int64
 47  estelionato                 37314 non-null  int64
 48  apreensao_drogas            37314 non-null  int64
 49  posse_drogas                32668 non-null  float64
 50  trafico_drogas              32668 non-null  float64
 51  apreensao_drogas_sem_autor  32668 non-null  float64
 52  recuperacao_veiculos        37314 non-null  int64
 53  apf                         32668 non-null  float64
 54  aaapai                      32668 non-null  float64
 55  cmp                         32668 non-null  float64
 56  cmba                        32668 non-null  float64
 57  ameaca                      37314 non-null  int64
 58  pessoas_desaparecidas       37314 non-null  int64
 59  encontro_cadaver            37314 non-null  int64
 60  encontro_ossada             37314 non-null  int64
 61  pol_militares_mortos_serv   37314 non-null  int64
 62  pol_civis_mortos_serv       37314 non-null  int64
 63  registro_ocorrencias        37314 non-null  int64
 64  fase                        37314 non-null  int64
dtypes: float64(12), int64(50), str(3)
memory usage: 18.5 MB

In [179]:
# Exibe dados estatísticos das colunas numéricas
df.describe()

,cisp,mes,ano,aisp,risp,mcirc,hom_doloso,lesao_corp_morte,latrocinio,cvli,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
count,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,3.731400e+04,37314.000000,37314.000000,37314.000000,37314.000000,...,32668.000000,32668.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000,37314.000000
mean,81.724259,6.482232,2014.188723,20.148470,3.869942,3.791939e+06,2.925256,0.028140,0.095380,3.048775,...,8.741306,0.641545,41.308731,3.223964,0.360481,0.022967,0.013400,0.002224,444.005306,2.985314
std,48.320410,3.461767,6.625316,11.348509,2.011450,1.741132e+06,4.327953,0.179516,0.366265,4.443058,...,14.809300,1.640367,39.390699,4.160668,0.988235,0.181215,0.130895,0.049334,398.542615,0.120295
min,1.000000,1.000000,2003.000000,1.000000,1.000000,3.300100e+06,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,38.000000,3.000000,2008.000000,10.000000,2.000000,3.302601e+06,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,106.000000,3.000000
50%,78.000000,6.000000,2014.000000,20.000000,4.000000,3.304557e+06,1.000000,0.000000,0.000000,1.000000,...,5.000000,0.000000,30.000000,2.000000,0.000000,0.000000,0.000000,0.000000,370.000000,3.000000
75%,125.000000,9.000000,2020.000000,30.000000,6.000000,3.304557e+06,4.000000,0.000000,0.000000,4.000000,...,11.000000,1.000000,56.000000,5.000000,0.000000,0.000000,0.000000,0.000000,663.000000,3.000000
max,168.000000,12.000000,2026.000000,43.000000,7.000000,9.999999e+06,43.000000,6.000000,9.000000,43.000000,...,419.000000,60.000000,370.000000,191.000000,112.000000,10.000000,4.000000,2.000000,3185.000000,3.000000

In [180]:
# Exibe o número de linhas e colunas do dataframe
df.shape

(37314, 65)

In [181]:
# Exibe o nome das olunas do dataframe
df.columns

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [182]:
# Exibe linhas do dataframe indicadas por índice
df.iloc[0:5]

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3

In [183]:
# Exibe linhas do dataframe que atendam uma condição
df_rj = df.loc[df['munic'] == 'Rio de Janeiro']

In [184]:
df_rj.groupby('cisp')['furto_celular'].sum().reset_index()

    cisp  furto_celular
0      1          15487
1      4          13700
2      5          23969
3      6           6410
4      7           1485
5      9          14621
6     10          14370
7     11            392
8     12          16659
9     13           7405
10    14          17633
11    15           6994
12    16          25480
13    17           8335
14    18          13808
15    19           8609
16    20           5179
17    21           6851
18    22           5682
19    23           7228
20    24           4623
21    25           3967
22    26           3924
23    27           4587
24    28           4014
25    29           7920
26    30           3693
27    31           1675
28    32          12504
29    33           6041
30    34           6851
31    35          12007
32    36           5519
33    37           6566
34    38           3048
35    39           2855
36    40           2274
37    41           5373
38    42           7912
39    43           2810
40    44           3691
41    45             73

In [185]:
df_2024 = df.loc[df['ano'] == 2024]
df_2024.groupby('cisp')['pessoas_desaparecidas'].sum().reset_index()

     cisp  pessoas_desaparecidas
0       1                     14
1       4                     50
2       5                     55
3       6                     34
4       7                     18
..    ...                    ...
132   159                     17
133   165                     12
134   166                     60
135   167                     14
136   168                      4

[137 rows x 2 columns]

In [186]:
df_baixada_2020 = df.loc[(df['ano'] == 2020) & (df['regiao'] == 'Baixada Fluminense')]
df_baixada_2020.groupby('cisp')['pessoas_desaparecidas'].sum().reset_index()

    cisp  pessoas_desaparecidas
0     48                     25
1     50                     56
2     51                     10
3     52                     38
4     53                     52
5     54                    101
6     55                     57
7     56                     66
8     57                     30
9     58                     88
10    59                     55
11    60                     51
12    61                      7
13    62                     38
14    63                     19
15    64                    103
16    65                     19
17    66                     35
18    67                     16

In [187]:
# ETL => Extract, Transform, Load

In [188]:
dados_numpy = np.array([12, 15, 17, 20, 22, 25, 28, 30, 35, 40])

q1 = np.percentile(dados_numpy, 25)
q2 = np.percentile(dados_numpy, 50)
q3 = np.percentile(dados_numpy, 75)

print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2): {q2}')
print(f'Terceiro quartil (Q3): {q3}')

Primeiro quartil (Q1): 17.75
Segundo quartil (Q2): 23.5
Terceiro quartil (Q3): 29.5

In [189]:
array_furto_celular = np.array(df_furto_celular_cisp['furto_celular'])

q1_furto_celular = np.percentile(array_furto_celular, 25)
q2_furto_celular = np.percentile(array_furto_celular, 50)
q3_furto_celular = np.percentile(array_furto_celular, 75)
media_furto_celular = np.mean(array_furto_celular)
mediana_furto_celular = np.median(array_furto_celular)
distancia_furto_celular = (media_furto_celular - mediana_furto_celular) / mediana_furto_celular
iqr_furto_celular = q3_furto_celular - q1_furto_celular
lim_sup_furto_celular = q3_furto_celular + (1.5 * iqr_furto_celular)
lim_inf_furto_celular = q1_furto_celular - (1.5 * iqr_furto_celular)

print(f'Primeiro quartil (Q1): {q1_furto_celular}')
print(f'Segundo quartil (Q2): {q2_furto_celular}') # Mediana
print(f'Terceiro quartil (Q3): {q3_furto_celular}')
print(f'Média: {media_furto_celular}')
print(f'Mediana: {mediana_furto_celular}')
print(f'Distância entre média e mediana: {distancia_furto_celular}')
print(f'Distância em porcentagem: {distancia_furto_celular * 100}%')
print(f'Intervalo entre quartis (IQR): {iqr_furto_celular}')
print(f'Limite superior: {lim_sup_furto_celular}')
print(f'Limite inferior: {lim_inf_furto_celular}')

Primeiro quartil (Q1): 451.25
Segundo quartil (Q2): 1675.5
Terceiro quartil (Q3): 4580.0
Média: 3422.978260869565
Mediana: 1675.5
Distância entre média e mediana: 1.042959272378135
Distância em porcentagem: 104.29592723781349%
Intervalo entre quartis (IQR): 4128.75
Limite superior: 10773.125
Limite inferior: -5741.875

In [190]:
df_furto_celular_cisp_outliers = df_furto_celular_cisp.loc[df_furto_celular_cisp['furto_celular'] >= lim_sup_furto_celular]
df_furto_celular_cisp_outliers = df_furto_celular_cisp_outliers.sort_values(by='furto_celular', ascending=False)
df_furto_celular_cisp_outliers

    cisp  furto_celular
12    16          25480
2      5          23969
10    14          17633
8     12          16659
0      1          15487
5      9          14621
6     10          14370
14    18          13808
1      4          13700
28    32          12504
31    35          12007

In [191]:
df_menor_q1_furto_celulares = df_furto_celular_cisp.loc[df_furto_celular_cisp['furto_celular'] < q1_furto_celular]

df_menor_q1_furto_celulares = df_menor_q1_furto_celulares.sort_values(by='furto_celular')
#df_menor_q1_furto_celulares = df_menor_q1_furto_celulares.sort_values(by='furto_celular', ascending= False)

df_menor_q1_furto_celulares

     cisp  furto_celular
129   155             47
114   138             53
131   157             55
77     92             65
87    104             72
41     45             73
94    111             82
83     98             90
130   156            109
126   152            109
137   168            121
118   142            128
92    109            143
132   158            154
123   147            165
116   140            165
124   148            195
61     70            202
100   122            202
95    112            211
82     97            233
108   130            242
127   153            254
98    120            299
113   137            303
111   135            355
86    101            356
115   139            364
79     94            367
60     67            372
7      11            392
85    100            401
84     99            435
90    107            446
99    121            450

In [192]:
df_capital_2020 = df.loc[(df['ano'] == 2020) & (df['regiao'] == 'Capital')]
df_apreenssao_menores_capital_2020 = df_capital_2020.groupby('cisp')['aaapai'].sum().reset_index()

array_apreensao_menores_capital_2020 = np.array(df_apreenssao_menores_capital_2020['aaapai'])

q1_apreensao_menores_capital_2020 = np.percentile(array_apreensao_menores_capital_2020, 25)
q2_apreensao_menores_capital_2020 = np.percentile(array_apreensao_menores_capital_2020, 50)
q3_apreensao_menores_capital_2020 = np.percentile(array_apreensao_menores_capital_2020, 75)

In [193]:
df_maior_q3_apreensao_menores_capital_2020 = df_apreenssao_menores_capital_2020.loc[df_apreenssao_menores_capital_2020['aaapai'] > q3_apreensao_menores_capital_2020]
df_maior_q3_apreensao_menores_capital_2020 = df_maior_q3_apreensao_menores_capital_2020.sort_values(by='aaapai', ascending=False)

df_maior_q3_apreensao_menores_capital_2020

    cisp  aaapai
10    14   170.0
12    16   143.0
8     12   136.0
9     13   104.0
33    37   104.0
29    33    67.0
6     10    66.0
28    32    64.0
2      5    61.0
31    35    45.0

In [194]:
gestao_atual = [2023, 2024,  2025, 2026]
df_interior_atual = df.loc[(df['regiao'] == 'Interior') & (df['ano'].isin(gestao_atual))]
df_interior_atual

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
32305,70,1,2023,2023m01,35,4,Tanguá,3305752,Interior,0,...,3.0,0.0,8,0,0,0,0,0,68,3
32306,71,1,2023,2023m01,35,4,Itaboraí,3301900,Interior,1,...,6.0,0.0,26,2,0,0,0,0,454,3
32317,88,1,2023,2023m01,10,5,Barra do Pirai,3300308,Interior,2,...,8.0,0.0,22,1,0,0,0,0,261,3
32318,89,1,2023,2023m01,37,5,Resende,3304201,Interior,6,...,10.0,2.0,37,4,0,0,0,0,516,3
32319,90,1,2023,2023m01,28,5,Barra Mansa,3300407,Interior,6,...,8.0,0.0,61,0,0,0,0,0,480,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37309,159,1,2026,2026m01,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,2.0,0.0,37,1,0,0,0,0,157,2
37310,165,1,2026,2026m01,33,5,Mangaratiba,3302601,Interior,0,...,3.0,0.0,32,0,0,0,0,0,234,2
37311,166,1,2026,2026m01,33,5,Angra dos Reis,3300100,Interior,2,...,10.0,0.0,98,9,1,0,0,0,713,2
37312,167,1,2026,2026m01,43,5,Paraty,3303807,Interior,1,...,3.0,0.0,25,2,0,0,0,0,258,2
37313,168,1,2026,2026m01,28,5,Rio Claro,3304409,Interior,1,...,0.0,0.0,3,0,0,0,0,0,57,2

In [195]:
regiao_metropolitana = ['Belford Roxo', 'Cachoeiras de Macacu', 'Duque de Caxias', 'Guapimirim', 'Itaboraí', 'Itaguaí', 'Japeri', 'Magé', 'Maricá', 'Mesquita', 'Nilópolis', 'Niterói', 'Nova Iguaçu', 'Paracambi', 'Petrópolis', 'Queimados', 'Rio Bonito', 'Rio de Janeiro', 'São Gonçalo', 'São João de Meriti', 'Seropédica', 'Tanguá']
df_metropolitana_2024 = df.loc[(df['ano'] == 2024) & (df['munic'].isin(regiao_metropolitana))]
df_furto_cel_rm_24 = df_metropolitana_2024.groupby('cisp')['furto_celular'].sum().reset_index()

array_furtos_celular_metr_2024 = np.array(df_furto_cel_rm_24['furto_celular'])
media_furto_celular_metr_2024 = np.mean(array_furtos_celular_metr_2024)
mediana_furto_celular_metr_2024 = np.median(array_furtos_celular_metr_2024)
distancia_furto_celular_metr_2024 = (media_furto_celular_metr_2024 - mediana_furto_celular_metr_2024) / mediana_furto_celular_metr_2024

df_furto_cel_rm_24

    cisp  furto_celular
0      1           1104
1      4           1500
2      5           2259
3      6            580
4      7            222
..   ...            ...
71    82            204
72   105            127
73   106            161
74   119             36
75   159             17

[76 rows x 2 columns]

In [196]:
print(f'Média de furtos de celular na região metropolitana: {media_furto_celular_metr_2024}')
print(f'Mediana de furtos de celular na região metropolitana: {mediana_furto_celular_metr_2024}')
print(f'Distância entre média e mediana: {distancia_furto_celular_metr_2024}')
print(f'Distância em porcentagem: {round(distancia_furto_celular_metr_2024, 2) * 100}%')

Média de furtos de celular na região metropolitana: 454.0657894736842
Mediana de furtos de celular na região metropolitana: 229.5
Distância entre média e mediana: 0.978500171998624
Distância em porcentagem: 98.0%

In [197]:
munic = df.groupby('munic').size().reset_index(name='Quantidade')
munic.to_csv('municipios.csv', index=False, sep=';')

In [198]:
df_rj.columns

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [199]:
df_rj['ocorrencias_veiculos'] = df_rj['roubo_veiculo'] + df_rj['furto_veiculos']
df_rj_cisp_veiculos = df_rj.groupby('cisp')['ocorrencias_veiculos'].sum().reset_index().sort_values(by='ocorrencias_veiculos', ascending=False)
df_rj_cisp_veiculos.head()

    cisp  ocorrencias_veiculos
23    27                 39450
30    34                 37102
31    35                 33724
35    39                 32945
34    38                 26297

In [200]:
array_rj_cisp_veiculos = np.array(df_rj_cisp_veiculos['ocorrencias_veiculos'])
q1_rj_cisp_veiculos = np.percentile(array_rj_cisp_veiculos, 25)
q2_rj_cisp_veiculos = np.percentile(array_rj_cisp_veiculos, 50)
q3_rj_cisp_veiculos = np.percentile(array_rj_cisp_veiculos, 75)
media_rj_cisp_veiculos = np.mean(array_rj_cisp_veiculos)
mediana_rj_cisp_veiculos = np.median(array_rj_cisp_veiculos)
distancia_rj_cisp_veiculos = (media_rj_cisp_veiculos - mediana_rj_cisp_veiculos) / mediana_rj_cisp_veiculos
iqr_rj_cisp_veiculos = q3_rj_cisp_veiculos - q1_rj_cisp_veiculos
lim_sup_rj_cisp_veiculos = q3_rj_cisp_veiculos + (1.5 * iqr_rj_cisp_veiculos)
lim_inf_rj_cisp_veiculos = q1_rj_cisp_veiculos - (1.5 * iqr_rj_cisp_veiculos)

print(f'Primeiro quartil (Q1): {q1_rj_cisp_veiculos}')
print(f'Segundo quartil (Q2): {q2_rj_cisp_veiculos}') # Mediana
print(f'Terceiro quartil (Q3): {q3_rj_cisp_veiculos}')
print(f'Média: {media_rj_cisp_veiculos}')
print(f'Mediana: {mediana_rj_cisp_veiculos}')
print(f'Distância entre média e mediana: {distancia_rj_cisp_veiculos}')
print(f'Distância em porcentagem: {distancia_rj_cisp_veiculos * 100}%')
print(f'Intervalo entre quartis (IQR): {iqr_rj_cisp_veiculos}')
print(f'Limite superior: {lim_sup_rj_cisp_veiculos}')
print(f'Limite inferior: {lim_inf_rj_cisp_veiculos}')

Primeiro quartil (Q1): 5093.25
Segundo quartil (Q2): 12824.5
Terceiro quartil (Q3): 18242.75
Média: 14116.47619047619
Mediana: 12824.5
Distância entre média e mediana: 0.10074281184265982
Distância em porcentagem: 10.074281184265981%
Intervalo entre quartis (IQR): 13149.5
Limite superior: 37967.0
Limite inferior: -14631.0

In [201]:
outliers_rj_cisp_veiculos = df_rj_cisp_veiculos.loc[df_rj_cisp_veiculos['ocorrencias_veiculos'] >= lim_sup_rj_cisp_veiculos]
outliers_rj_cisp_veiculos

    cisp  ocorrencias_veiculos
23    27                 39450

In [202]:
max_ano = max(df['ano'])
df_decada = df.loc[df['ano'] > max_ano - 10]
df_decada

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
22357,1,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,0,...,4.0,0.0,12,0,0,0,0,0,375,3
22358,4,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,1,...,19.0,1.0,20,2,1,0,0,0,630,3
22359,5,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,0,...,17.0,3.0,26,1,0,0,0,0,836,3
22360,6,1,2017,2017m01,4,1,Rio de Janeiro,3304557,Capital,1,...,11.0,0.0,18,2,0,0,0,0,482,3
22361,7,1,2017,2017m01,5,1,Rio de Janeiro,3304557,Capital,3,...,4.0,0.0,10,0,0,0,0,0,230,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37309,159,1,2026,2026m01,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,2.0,0.0,37,1,0,0,0,0,157,2
37310,165,1,2026,2026m01,33,5,Mangaratiba,3302601,Interior,0,...,3.0,0.0,32,0,0,0,0,0,234,2
37311,166,1,2026,2026m01,33,5,Angra dos Reis,3300100,Interior,2,...,10.0,0.0,98,9,1,0,0,0,713,2
37312,167,1,2026,2026m01,43,5,Paraty,3303807,Interior,1,...,3.0,0.0,25,2,0,0,0,0,258,2
37313,168,1,2026,2026m01,28,5,Rio Claro,3304409,Interior,1,...,0.0,0.0,3,0,0,0,0,0,57,2

In [207]:
df_decada['regiao'] = df_decada['regiao'].replace({'Grande NiterÃÂÃÂÃÂÃÂ³i': 'Grande Niterói'})

In [208]:
df_decada_regiao_furto_veiculo = df_decada.groupby('regiao')['furto_veiculos'].sum().reset_index().sort_values(by='furto_veiculos', ascending=False)
df_decada_regiao_furto_veiculo

               regiao  furto_veiculos
1             Capital           67139
0  Baixada Fluminense           36978
3            Interior           22261
2      Grande Niterói           17616

In [209]:
array_dec_reg_fur_vei = np.array(df_decada_regiao_furto_veiculo['furto_veiculos'])
q1_dec_reg_fur_vei = np.percentile(array_dec_reg_fur_vei, 25)
q2_dec_reg_fur_vei = np.percentile(array_dec_reg_fur_vei, 50)
q3_dec_reg_fur_vei = np.percentile(array_dec_reg_fur_vei, 75)
media_dec_reg_fur_vei = np.mean(array_dec_reg_fur_vei)
mediana_dec_reg_fur_vei = np.median(array_dec_reg_fur_vei)
distancia_dec_reg_fur_vei = (media_dec_reg_fur_vei - mediana_dec_reg_fur_vei) / mediana_dec_reg_fur_vei
iqr_dec_reg_fur_vei = q3_dec_reg_fur_vei - q1_dec_reg_fur_vei
lim_sup_dec_reg_fur_vei = q3_dec_reg_fur_vei + (1.5 * iqr_dec_reg_fur_vei)
lim_inf_dec_reg_fur_vei = q1_dec_reg_fur_vei - (1.5 * iqr_dec_reg_fur_vei)

print(f'Primeiro quartil (Q1): {q1_dec_reg_fur_vei}')
print(f'Segundo quartil (Q2): {q2_dec_reg_fur_vei}') # Mediana
print(f'Terceiro quartil (Q3): {q3_dec_reg_fur_vei}')
print(f'Média: {media_dec_reg_fur_vei}')
print(f'Mediana: {mediana_dec_reg_fur_vei}')
print(f'Distância entre média e mediana: {distancia_dec_reg_fur_vei}')
print(f'Distância em porcentagem: {distancia_dec_reg_fur_vei * 100}%')
print(f'Intervalo entre quartis (IQR): {iqr_dec_reg_fur_vei}')
print(f'Limite superior: {lim_sup_dec_reg_fur_vei}')
print(f'Limite inferior: {lim_inf_dec_reg_fur_vei}')

Primeiro quartil (Q1): 21099.75
Segundo quartil (Q2): 29619.5
Terceiro quartil (Q3): 44518.25
Média: 35998.5
Mediana: 29619.5
Distância entre média e mediana: 0.21536487786762099
Distância em porcentagem: 21.5364877867621%
Intervalo entre quartis (IQR): 23418.5
Limite superior: 79646.0
Limite inferior: -14028.0

In [211]:
outliers_decada_regiao_furto_veiculo = df_decada_regiao_furto_veiculo.loc[df_decada_regiao_furto_veiculo['furto_veiculos'] >= lim_sup_dec_reg_fur_vei]
outliers_decada_regiao_furto_veiculo

Empty DataFrame
Columns: [regiao, furto_veiculos]
Index: []