In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.float_format', '{:.2f}'.format)

In [3]:
def agrupar_soma(df, qual, quant='Valor de Venda', menorMaior=False):
    return df.groupby(qual)[quant].sum().reset_index().sort_values(by=quant, ascending=menorMaior)

In [4]:
def aplicar_loc(df, col_condicao, valor_condicao, sinal):
    if sinal == '==':
        return df.loc[df[col_condicao] == valor_condicao]
    elif sinal == '>':
        return df.loc[df[col_condicao] > valor_condicao]
    elif sinal == '<':
        return df.loc[df[col_condicao] < valor_condicao]
    else:
        print('Operação Inválida!')
        return

In [5]:
def criar_array(df, coluna='Valor de Venda'):
    return np.array(df[coluna])

In [6]:
def calcular_quartis(df, coluna='Valor de Venda'):
    array = criar_array(df, coluna)
    q1 = np.percentile(array, 25)
    q2 = np.percentile(array, 50)
    q3 = np.percentile(array, 75)

    return [q1, q2, q3]

In [7]:
def calcular_distancia(df, coluna='Valor de Venda'):
    array = criar_array(df, coluna)
    media = np.mean(array)
    mediana = np.median(array)

    return (media - mediana) / mediana

In [8]:
def calcular_limites(df, coluna='Valor de Venda'):
    quartis = calcular_quartis(df, coluna)

    iqr = quartis[2] - quartis[0]

    lim_sup = quartis[2] + (1.5 * iqr)
    lim_inf = quartis[0] - (1.5 * iqr)

    return [lim_sup, lim_inf]

In [9]:
def mostrar_dist_lim(dist, lim):
    print(f'Distância: {dist}')
    print(f'Limite Superior: {lim[0]}')
    print(f'Limite Inferior: {lim[1]}')

In [10]:
dados = '../csv/CARAMELO2.csv'
df = pd.read_csv(dados, sep=';')
df.head()

,ID Venda,Loja,ID Loja,Estado Loja,Cidade Loja,Nome Cliente,ID Cliente,Sexo,Idade,Estado Cliente,Cidade Cliente,ID Produto,Categoria Produto,Marca,Data da Compra,Data da Entrega,Metodo de Pagamento,Produto,Valor de Venda
0,1,Melo,49,BA,Salvador,Lucas Silveira,35727,Masculino,24,BA,Vitória da Conquista,946,Eletrônicos,Lenovo,2024-12-20,2024-12-30,Pix,Drone,"8979,56"
1,10,Mendonça Machado Ltda.,7,SP,Sorocaba,Isabella Campos,2188,Feminino,41,MG,Uberlândia,112,Eletrônicos,Apple,2023-11-22,2023-11-28,Dinheiro,Celular,"112146,00"
2,1000,Cunha Mendes S.A.,97,BA,Camaçari,Marcela Barbosa,2293,Feminino,47,SP,Sorocaba,283,Alimentos,Del Valle,2023-08-25,2023-08-27,Dinheiro,Suco,"37,08"
3,100001,Nunes,77,MG,Contagem,Ravy Cunha,38559,Feminino,59,RJ,Petrópolis,805,Eletrônicos,Dell,2024-08-03,2024-08-04,Dinheiro,Notebook,"13455,14"
4,100007,Cunha Mendes S.A.,97,BA,Camaçari,Sra. Ana Cecília Pinto,19274,Masculino,27,SP,São Paulo,362,Alimentos,Coca-Cola,2023-02-28,2023-03-08,Pix,Refrigerante,"17,33"

In [11]:
df['Valor de Venda'] = df['Valor de Venda'].str.replace(',', '.').astype(float)
df.head()

,ID Venda,Loja,ID Loja,Estado Loja,Cidade Loja,Nome Cliente,ID Cliente,Sexo,Idade,Estado Cliente,Cidade Cliente,ID Produto,Categoria Produto,Marca,Data da Compra,Data da Entrega,Metodo de Pagamento,Produto,Valor de Venda
0,1,Melo,49,BA,Salvador,Lucas Silveira,35727,Masculino,24,BA,Vitória da Conquista,946,Eletrônicos,Lenovo,2024-12-20,2024-12-30,Pix,Drone,8979.56
1,10,Mendonça Machado Ltda.,7,SP,Sorocaba,Isabella Campos,2188,Feminino,41,MG,Uberlândia,112,Eletrônicos,Apple,2023-11-22,2023-11-28,Dinheiro,Celular,112146.00
2,1000,Cunha Mendes S.A.,97,BA,Camaçari,Marcela Barbosa,2293,Feminino,47,SP,Sorocaba,283,Alimentos,Del Valle,2023-08-25,2023-08-27,Dinheiro,Suco,37.08
3,100001,Nunes,77,MG,Contagem,Ravy Cunha,38559,Feminino,59,RJ,Petrópolis,805,Eletrônicos,Dell,2024-08-03,2024-08-04,Dinheiro,Notebook,13455.14
4,100007,Cunha Mendes S.A.,97,BA,Camaçari,Sra. Ana Cecília Pinto,19274,Masculino,27,SP,São Paulo,362,Alimentos,Coca-Cola,2023-02-28,2023-03-08,Pix,Refrigerante,17.33

In [12]:
df_venda_loja = agrupar_soma(df, 'Loja')
df_venda_loja.head()

                      Loja  Valor de Venda
10  Mendonça Machado Ltda.     73919670.56
7                    Gomes     39371215.05
6                Fernandes     37107099.24
0                  Andrade     36868599.90
3                    Cunha     36133723.77

In [13]:
df_venda_loja.tail()

                     Loja  Valor de Venda
8                 Machado     15438498.57
4        Cunha Gomes - EI     15287724.29
16                 Santos     15090433.84
14  Ribeiro Sampaio Ltda.     15053199.25
9                    Melo     14618426.65

In [14]:
dist_venda_loja = calcular_distancia(df_venda_loja)
lim_venda_loja = calcular_limites(df_venda_loja)

mostrar_dist_lim(dist_venda_loja, lim_venda_loja)

Distância: 0.41684638521293527
Limite Superior: 65856281.29500001
Limite Inferior: -14651972.625000007

In [27]:
outliers_venda_loja = aplicar_loc(df_venda_loja, 'Valor de Venda', lim_venda_loja[0], '>')
outliers_venda_loja

                      Loja  Valor de Venda
10  Mendonça Machado Ltda.     73919670.56

In [17]:
df_venda_uf = agrupar_soma(df, 'Estado Loja')
df_venda_uf

  Estado Loja  Valor de Venda
4          SP    258909982.03
2          RJ     98194095.13
3          RS     62016085.46
1          MG     45855604.40
0          BA     30622494.10

In [18]:
dist_venda_uf = calcular_distancia(df_venda_uf)
lim_venda_uf = calcular_limites(df_venda_uf)

mostrar_dist_lim(dist_venda_uf, lim_venda_uf)

Distância: 0.5982894032860485
Limite Superior: 176701831.225
Limite Inferior: -32652131.695

In [19]:
outliers_venda_uf = aplicar_loc(df_venda_uf, 'Valor de Venda', lim_venda_uf[0], '>')
outliers_venda_uf

  Estado Loja  Valor de Venda
4          SP    258909982.03

In [20]:
df_venda_cat_prod = agrupar_soma(df, 'Categoria Produto')
df_venda_cat_prod

  Categoria Produto  Valor de Venda
1       Eletrônicos    398284376.66
3            Móveis     78552157.79
4            Roupas     14495598.61
0         Alimentos      2892560.74
2            Livros      1373567.32

In [21]:
dist_venda_cat_prod = calcular_distancia(df_venda_cat_prod)
lim_venda_cat_prod = calcular_limites(df_venda_cat_prod)

mostrar_dist_lim(dist_venda_cat_prod, lim_venda_cat_prod)

Distância: 5.837913693030992
Limite Superior: 192041553.365
Limite Inferior: -110596834.83500002

In [22]:
outliers_venda_cat_prod = aplicar_loc(df_venda_cat_prod, 'Valor de Venda', lim_venda_cat_prod[0], '>')
outliers_venda_cat_prod

  Categoria Produto  Valor de Venda
1       Eletrônicos    398284376.66

In [23]:
df_venda_prod = agrupar_soma(df, 'Produto')
df_venda_prod.head()

           Produto  Valor de Venda
48         Teclado     52449847.31
12         Celular     51362657.26
20  Fone de Ouvido     49368227.23
31        Notebook     34446750.39
30           Mouse     33362050.01

In [24]:
df_venda_prod.tail()

                   Produto  Valor de Venda
36   Orgulho e Preconceito       134024.75
0                     1984       132745.02
35      O Senhor dos Anéis       130492.37
32       O Código Da Vinci       126218.56
1   A Culpa é das Estrelas       124794.37

In [25]:
dist_venda_prod = calcular_distancia(df_venda_prod)
lim_venda_prod = calcular_limites(df_venda_prod)

mostrar_dist_lim(dist_venda_prod, lim_venda_prod)

Distância: 6.045102758697682
Limite Superior: 20108462.9775
Limite Inferior: -11623575.8825

In [26]:
outliers_venda_prod = aplicar_loc(df_venda_prod, 'Valor de Venda', lim_venda_prod[0], '>')
outliers_venda_prod

                 Produto  Valor de Venda
48               Teclado     52449847.31
12               Celular     51362657.26
20        Fone de Ouvido     49368227.23
31              Notebook     34446750.39
30                 Mouse     33362050.01
47                Tablet     33088129.29
14  Console de Videogame     31663357.68
29               Monitor     30621309.99
46                    TV     28401147.89
43            Smartwatch     27830646.35
16                 Drone     25690253.26

In [29]:
outliers_venda_cat_prod.to_csv('../csv/outliers_categoria_produto.csv')
outliers_venda_loja.to_csv('../csv/outliers_loja.csv')
outliers_venda_prod.to_csv('../csv/outliers_produto.csv')
outliers_venda_uf.to_csv('../csv/outliers_estado.csv')